name: Extract M3U8 From Elahmad

on:
  schedule:
    - cron: "*/15 * * * *"    # كل 15 دقيقة
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Scraper
        run: node fetch-video.js

      - name: Push m3u8.json to el-links repo
        run: |
          if [ -f m3u8.json ]; then
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            
            # استنسخ مستودع el-links
            git clone https://x-access-token:${{ secrets.EL_LINKS_TOKEN }}@github.com/imagesloads/el-links.git links-repo
            
            cp m3u8.json links-repo/m3u8.json
            
            cd links-repo
            git add m3u8.json
            git commit -m "Update m3u8" || echo "No changes"
            git push
          else
            echo "⚠️ لا يوجد ملف m3u8.json"
          fi
